<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="MAIN" Id="{46b87271-a47f-40d1-9e75-510d5206adec}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	aEvents : ARRAY[1..100] OF ST_Event;
	sTempString : STRING(255);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[sTempString := aEvents[33].sEventText;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>